const MOVIE_URL = 'https://api.nomoreparties.co';
const MAIN_URL = 'https://api.movie.diak.nomoredomains.club';
const SHORTMOVIES_DURATION = 40;
const MORE_CARDS_FOR_DESKTOP = 3;
const SHOW_CARDS_FOR_DESKTOP = 12;
const MORE_CARDS_FOR_TABLET_AND_PHONE = 2;
const SHOW_CARDS_FOR_TABLET = 8;
const SHOW_CARDS_FOR_PHONE = 5;

export {
  MOVIE_URL, MAIN_URL, 
  SHORTMOVIES_DURATION,
  MORE_CARDS_FOR_DESKTOP,
  SHOW_CARDS_FOR_DESKTOP,
  MORE_CARDS_FOR_TABLET_AND_PHONE,
  SHOW_CARDS_FOR_TABLET,
  SHOW_CARDS_FOR_PHONE
}